### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by kyziq** [Kyziq/college-dorm-admission-through-coupons-system#2]
### Task List

- [x] For option 2, add input for user to enter activity id, if activity id is valid, add coupon to student
- [x] Add option to exit looping for user
- [x] Add option to view all students registered
- [x] Add option to view all activities registered
- [x] Change vector data structure
- [x] Add exception handling. For example, check if the file successfully opened or not, if not, give error message
- [ ] Change output to table form

**Comment by kyziq** [comment]
- [ ] During registration, add a function to check if the student number already exists or not
